#!/bin/sh

scriptversion=2010-05-09.22; # UTC

# Copyright (C) 2010, 2011 Free Software Foundation, Inc.

# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

# Additional permission under GNU GPL version 3 section 7


# Written by Giuseppe Scrivano.

if test -f .tarball-version
then
    cat .tarball-version | tr -d '\n'
    exit 0
fi

DIRTY=""

test -n "$(bzr diff | tr -d '\n')" && DIRTY="-dirty"

REVNO=$(bzr revno)

TAG=$(bzr tags -r $REVNO | cut -d' ' -f1)
if test -z "$TAG"
then
    TAG=$(bzr tags -r ..$REVNO | cut -d' ' -f1)

    # No tags yet
    if test -z "$1"
    then
        test -z "$TAG" && TAG="unknown"
    else
        TAG=$1
    fi

    TAG=$TAG.$REVNO
fi


printf "%s%s" "$TAG" "$DIRTY"

# Local variables:
# eval: (add-hook 'write-file-hooks 'time-stamp)
# time-stamp-start: "scriptversion="
# time-stamp-format: "%:y-%02m-%02d.%02H"
# time-stamp-time-zone: "UTC"
# time-stamp-end: "; # UTC"
# End:
