.TH PLANK "1"
.SH NAME
Plank \- Stupidly simple.
.SH SYNOPSIS
plank [\fIoptions\fR]
.SH OPTIONS
.TP
\fB\-d\fR \fB\-\-debug\fR
Enable debug level logging
.SH HOMEPAGE
For more information, please visit http://launchpad.net/plank/
.SH AUTHORS
Robert Dyer <psybers@gmail.com>, Daniel Foré <daniel.p.fore@gmail.com>, Rico Tzschichholz <ricotz@t-online.de>
